<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Aerospike.Examples</RootNamespace>
    <AssemblyName>aerospike-tls-example</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aerospike.Client" Version="8.4.2" />
  </ItemGroup>

</Project>
